spring:
  kafka:
    properties:
      default:
        deserialization:
          exception:
            handler: org.apache.kafka.streams.errors.LogAndContinueExceptionHandler
    consumer:
      group-id: @project.artifactId@
  application:
    name: @project.artifactId@

build:
  version: @project.version@
  description: @project.description@
